default_language_version:
  python: python3.9

repos:
  - repo: local
    hooks:
    - id: flake8
      name: flake8
      description: wemake-python-styleguide enforcement
      entry: flake8
      args: ["--config=setup.cfg"]
      language: python
      types: [python]
  - repo: local  # finds unused code
    hooks:
      - id: vulture
        name: vulture
        entry: vulture
        language: python
        types: [python]
        args: ["--min-confidence", "90"]
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=2048']
      - id: check-toml
      - id: check-yaml
        args:
          - '--unsafe'
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: double-quote-string-fixer
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
  - repo: local
    hooks:
      - id: black
        name: black   # Add this line
        entry: black
        language: python
        types: [python]
        args: ["--skip-string-normalization", "--line-length=120"]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.5.1
    hooks:
      - id: add-trailing-comma
  - repo: 'https://github.com/kynan/nbstripout'  # delete outputs from .ipynb
    rev: 0.6.1
    hooks:
      - id: nbstripout
